CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS shorturls (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    userId INTEGER,
    FOREIGN KEY (userId) REFERENCES users (id)
);
